version: '3.3'

services:


  sb-mysql57:
    container_name: sb-mysql57
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - ../_spring-boot-test_mysql57:/var/lib/mysql
      - ../_spring-boot-test_mysql57_log:/var/log/mysql
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '8605:3306'
    environment:
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_USER=$DB_USERNAME
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      # - MYSQL_ROOT_HOST=%
    command: --max_allowed_packet=128M  --innodb_buffer_pool_size=512M --wait_timeout=3600 --interactive_timeout=3600 --connect_timeout=600 --net_read_timeout=600 --net_write_timeout=600 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      sb:
        ipv4_address: 172.40.0.5


  sb-mdb:
    container_name: sb-mdb
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - ../_spring-boot-test_mongo:/data/db
      - ../_spring-boot-test_mongo-log:/var/log/mongodb
      - ../_spring-boot-test_mongo-dmp:/dmp
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '8607:27017'
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: $DB_USERNAME
#      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
    networks:
      sb:
        ipv4_address: 172.40.0.7


  sb:
    container_name: sb
    image: sp-boot/test:1
    restart: unless-stopped
    depends_on:
      - sb-mysql57
      - sb-mdb
    ports:
      - '8602:8500'
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      sb:
        ipv4_address: 172.40.0.2


networks:
  sb:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.40.0.0/24